List jobList = [
  {"category": "All in Jobs", "subcategory": []},
  {
    "category": "Jobs Available",
    "subcategory": [
      "Jobs Available",
      "Architecture & Interior Design",
      "Art & Entertainment",
      "Automotive",
      "Airlines & Aviation",
      "Banking & Finance",
      "Business Development",
      "Business Supplies & Equipment",
      "Beauty",
      "Education",
      "Customer Service",
      "Consulting",
      "Engineering",
      "Environmental Services",
      "Event Management",
      "Executive",
      "Fashion",
      "Food & Beverages",
      "Government/Administration",
      "Graphic Design",
      "Hospitality &  Restaurants",
      "HR & Recruitment",
      "Import & Export",
      "Industrial & Manufacturing",
      "Information Technology",
      "Insurance",
      "Legal Services",
      "Logistics & Distribution",
      "Marketing & Advertising",
      "Media",
      "Medical & Healthcare",
      "Oil, Gas & Energy",
      "Online Media",
      "Pharmaceuticals",
      "Public Relations",
      "Real Estate",
      "Research & Development",
      "Retail & Consumer Goods",
      "Safety & Security",
      "Sales",
      "Secretarial",
      "Sports & Fitness",
      "Telecommunications",
    ]
  },
  {
    "category": "Jobs Wanted",
    "subcategory": [
      "Jobs Wanted",
      "Architecture & Interior Design",
      "Art & Entertainment",
      "Automotive",
      "Airlines & Aviation",
      "Banking & Finance",
      "Business Development",
      "Business Supplies & Equipment",
      "Beauty",
      "Education",
      "Customer Service",
      "Consulting",
      "Engineering",
      "Environmental Services",
      "Event Management",
      "Executive",
      "Fashion",
      "Food & Beverages",
      "Government/Administration",
      "Graphic Design",
      "Hospitality &  Restaurants",
      "HR & Recruitment",
      "Import & Export",
      "Industrial & Manufacturing",
      "Information Technology",
      "Insurance",
      "Legal Services",
      "Logistics & Distribution",
      "Marketing & Advertising",
      "Media",
      "Medical & Healthcare",
      "Oil, Gas & Energy",
      "Online Media",
      "Pharmaceuticals",
      "Public Relations",
      "Real Estate",
      "Research & Development",
      "Retail & Consumer Goods",
      "Safety & Security",
      "Sales",
      "Secretarial",
      "Sports & Fitness",
      "Telecommunications",
    ]
  },
];
